### PR TITLE
allow taking in nifti file rather than filename

### PR DESCRIPTION
**Pull request by cancan101**
Depends on https://github.com/nipy/niwidgets/pull/17
closes https://github.com/nipy/niwidgets/issues/12

### CODE REVIEW

**Comment by janfreyberg** [comment]
Looks great - although I think we should now change the argument `filename` to something that reflects the two options for passing in data better, maybe `image` or something like that. And it would be great to update the docstring, as well.

**Comment by cancan101** [comment]
sure, feel free to push more commits to this PR.

**Comment by cancan101** [comment]
@janfreyberg Do you think you will have to get to this? Otherwise I can take a stab at finishing up PR.

**Comment by janfreyberg** [comment]
Hey, sorry - I've been a bit busy lately so haven't had much time to look after this project. I can just merge this and then make the improvements later - I think that's probably the easiest way to go about it.

**Comment by cancan101** [comment]
sure, sounds good. I would merge: https://github.com/nipy/niwidgets/pull/17 first and then I can rebase this

**Comment by janfreyberg** [comment]
Done!

**Comment by cancan101** [comment]
rebased

**Comment by janfreyberg** [comment]
Excellent, thanks

**Pull request merged**
