### PR TITLE
more efficient figure updates, 4D image functionality

### PR DESCRIPTION
**Pull request by bilgelm**
Interactive figure updates in _default_plotter now only change the data in the existing figure rather than regenerate the entire figure handle. Added 4D image functionality to _default_plotter.
TODO: account for image orientation

(niwidget_surface.py is what we had at the end of NHW; Melanie might have an updated version of this.)

### CODE REVIEW

**Comment by janfreyberg** [comment]
Looks great, it's much smoother!

Any idea why it's producing one static version of the figure on first call?

image

**Comment by janfreyberg** [comment]
@bilgelm I just merged @melanieganz's surface_widget branch, could you pull from master again to clear up the conflicts?

**Comment by bilgelm** [comment]
@janfreyberg not sure why the widget produces two images on the first call. will take a look at the surface viz code.

**Comment by melanieganz** [comment]
@bilgelm were you able to figure out the visualization of two figures issue?

**Comment by janfreyberg** [comment]
@melanieganz @bilgelm I think I've figured out why - it only happens when `%matplotlib inline` is used in the notebook. Adding `plt.ioff()` before the widget creation and `plt.ion()` afterwards prevents matplotlib for drawing the figure _inline_, and means only the widget component gets drawn.

@bilgelm, can you allow me push access to this pull request ([see here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/))? I'll push my fixes (plus some minor re-organisation of the code) and merge then.

**Comment by bilgelm** [comment]
Sorry for taking a long time to get back! I resolved the conflicts. @melanieganz the surface widget is working beautifully (my installation must have been wrong when I tried it out last time). @janfreyberg good catch with `%matplotlib inline`. This PR is set to "Allow edits from maintainers" so you should be able to push - let me know if there are issues. You've probably already fixed the bug that prevents NiftiWidget's `_custom_plotter` from working.

**Pull request closed without merging**
