### PR TITLE
Added a niwidget for surfaces called niwidget_surface. The functional…

### PR DESCRIPTION
**Pull request by melanieganz**
…ity is the same as for the original niwidget, but specific for visualizing surfaces. Also added toy data to show the functionality.

### CODE REVIEW

**Comment by janfreyberg** [comment]
Wow! I love this!

A couple of things that I would love to see before merging this:

- moving the example notebook into the root folder rather than `niwidgets/` (although in the future we'll just merge this into the main example notebook
- moving the `data` directory into `niwidgets/data` and renaming the folder `006` into something like `example_surfaces`. We can then make this importable via `niwidgets.exampledata`. I find that more helpful for developing. To make sure it ships when people `pipinstall` the package you'd have to add the necessary file identifiers to this line: https://github.com/nipy/niwidgets/blob/master/setup.py#L30

**Comment by melanieganz** [comment]
Hi Jan, I am glad you like it. I have made the proposed directory structure changes and updated the demo notebook in order to reflect them (2 different commits above). The last thing you are asking for regarding the pipinstall, I am not quite sure how to do  yet (sorry, have never tried to make a python package before), but am reading up on it. So coming soon.

**Comment by melanieganz** [comment]
Ok, this should be it I guess.

**Comment by janfreyberg** [comment]
Awesome, thanks.

Thanks for fixing the error message as well. However, it would be cool if the exception matched the problem. If you could change `raise ValueError(...)` to `raise IOError(...)`, that would be great (also see here: https://docs.python.org/2.7/library/exceptions.html#exceptions.IOError)

**Comment by melanieganz** [comment]
Thanks for the input! That helps me learn. Whenever I checked if a file exists or not, I changed it to an IOError.

**Comment by janfreyberg** [comment]
@arokem this looks good to me now. I'd merge, but can't (don't have write access)

**Comment by arokem** [comment]
Whoops. Sorry about that - I just made you an admin on this repo.

**Pull request merged**
